import re

SUPPORTED_GRADES = [7, 8, 9, 10]
SCHOOL_YEAR_PATTERN = re.compile(r"^\d{4}-\d{4}$")
LRN_PATTERN = re.compile(r"^\d{12}$")
SUPPORTED_UPLOAD_EXTENSIONS = {".xls", ".xlsx", ".csv"}
MAX_UPLOAD_SIZE_MB = 50
PENDING_UPLOAD_TTL_SECONDS = 900
EDITABLE_RECORD_STATUSES = ["ENROLLED", "TRANSFER_IN", "PENDING_TRANSFER_IN", "TRANSFER_OUT"]
PER_PAGE = 10
